### ISSUE TITLE
Signing fails using Squirrel (2.6.2-pre+126925)

### ISSUE THREAD

**Issue by mitjaahlin** [clowd/Clowd.Squirrel#14]
Hi,
I'm having problems signing my application files using the "new" command squirrel pack.
The command is executed using custom publish target in VS .csproj.

Command:
`<Exec Command="squirrel pack --packName=APPNAME --releaseDir=..\Version_Releases --packVersion=VERSION --packAuthors=&quot;COMPANY&quot; --no-delta --splashImage=.\APP_splash.png --packDirectory=bin\publish --setupIcon=.\Assets\APPBeli.ico --signParams=&quot;/t&#160;http://timestamp.digicert.com&#160;/sha1&#160;HASH&quot;" />`

ERROR:
[ERRO] System.AggregateException: One or more errors occurred. (**Failed to sign, command invoked was: 'C:\Users\usr\.nuget\packages\clowd.squirrel\2.6.2-pre\tools\signtool.exe sign /t http://timestamp.digicert.com /sha1 HASH C:\Users\usr\AppData\Local\SquirrelTemp\tempd\lib\app\e_sqlite3.dll'**)
 ---> System.Exception: Failed to sign, command invoked was: 'C:\Users\usr\.nuget\packages\clowd.squirrel\2.6.2-pre\tools\signtool.exe sign /t http://timestamp.digicert.com /sha1 HASH C:\Users\usr\AppData\Local\SquirrelTemp\tempd\lib\app\e_sqlite3.dll'
   at SquirrelCli.Program.signPEFile(String exePath, String signingOpts)
   at SquirrelCli.Program.<>c__DisplayClass9_0.<<Releasify>b__16>d.MoveNext()
--- End of stack trace from previous location ---
   at Squirrel.Utility.<>c__DisplayClass13_11.<<ForEachAsync>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at SquirrelCli.Program.<>c__DisplayClass9_0.<Releasify>b__7(String pkgPath)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, Func2 releaseNotesProcessor, Action1 contentsPostProcessHook)
   at SquirrelCli.Program.Releasify(ReleasifyOptions options)
   at SquirrelCli.Program.Pack(PackOptions options)
   at SquirrelCli.CommandAction1.Execute(IEnumerable1 args)
   at SquirrelCli.CommandSet.Execute(String[] args)
   at SquirrelCli.Program.Main(String[] args)

The "SIGN" command is executed successfully using powershell.
The nbsp character `(&#160;)` was needed to use all the input parameters for sign command.

**Comment by caesay** [comment]
Hi, thanks for trying my package. I have published a new version (2.6.28) which I believe fixes this issue with commit 9865845d62e0c9526cbeafd784f9600b86de7afb. Can you please test and let me know?

**Comment by mitjaahlin** [comment]
Hi, thanks for the quick response and commit.
Signing now works correctly using this command:
`<Exec Command="squirrel pack --packName=APPNAME --releaseDir=..\Version_Releases --packVersion=0.4.3 --packAuthors=&quot;AUTHOR&quot; --no-delta --splashImage=.\APP_splash.png --packDirectory=bin\publish --setupIcon=.\Assets\APPBeli.ico --signParams=&quot;/t http://timestamp.digicert.com /sha1 SHA" />`

I have just one question left... Before using this command "squirrel pack" I was packing the app with nuget command using hand made .nuspec file with net45 folder inside.
But now with squirrel pack iside there are two folders ("native" and "net45"). Can you please explain how to get rid of the "native" folder?

Thanks again for all the help and time spent on this repo.
Mitja

**Comment by caesay** [comment]
The `releasify` command still exists, if you prefer to use a custom .nuspec or control the structure of the package yourself. The `pack` command is for convenience, so you don't need to create a nuspec. The `pack` command will bundle your app into the `lib/native` folder (not into the net45 folder). 

Packages will be ~7mb larger using this library than they were with the previous version of Squirrel. See #7 for more info.

If you still believe there is an issue, and would like me to take a look, you can upload a produced nupkg or sample app here, or email it to me at git@caesay.com and I will check.

**Comment by mitjaahlin** [comment]
Now after successful packing Setup.exe fails with the following error:

[13/12/21 12:25:22] info: Program: Starting Squirrel Updater: --install .
[13/12/21 12:25:22] info: Program: Starting install, writing to C:\Users\mitja\AppData\Local\SquirrelTemp
[13/12/21 12:25:22] info: Program: About to install to: C:\Users\mitja\AppData\Local\GBot
[13/12/21 12:25:23] info: CheckForUpdateImpl: Reading RELEASES file from C:\Users\mitja\AppData\Local\SquirrelTemp
[13/12/21 12:25:23] info: CheckForUpdateImpl: First run, starting from scratch
[13/12/21 12:25:23] info: ApplyReleasesImpl: Writing files to app directory: C:\Users\mitja\AppData\Local\GBot\app-0.4.3
[13/12/21 12:25:24] info: LogHost: Rigging execution stub for GBot_ExecutionStub.exe to C:\Users\mitja\AppData\Local\GBot\GBot.exe
[13/12/21 12:25:24] info: ApplyReleasesImpl: Squirrel Enabled Apps: []
[13/12/21 12:25:24] warn: ApplyReleasesImpl: No apps are marked as Squirrel-aware! Going to run them all
[13/12/21 12:25:24] info: ApplyReleasesImpl: About to create shortcuts for GBot.exe, rootAppDir C:\Users\mitja\AppData\Local\GBot
[13/12/21 12:25:24] info: ApplyReleasesImpl: Creating shortcut for GBot.exe => C:\Users\mitja\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Grumson d.o.o.\GBot.lnk
[13/12/21 12:25:25] error: IEnableLogger: Can't write shortcut: C:\Users\mitja\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Grumson d.o.o.\GBot.lnk: System.NotSupportedException: Built-in COM has been disabled via a feature switch. See https://aka.ms/dotnet-illink/com for more information.
   at Squirrel.Shell.ShellLink..ctor()
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass5_1.<CreateShortcutsForExecutable>b__1()
   at Squirrel.Utility.<>c__DisplayClass8_0.<Retry>b__0()
   at Squirrel.Utility.Retry[T](Func1 block, Int32 retries)
   at Squirrel.Utility.Retry(Action block, Int32 retries)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass5_1.<CreateShortcutsForExecutable>b__0()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
[13/12/21 12:25:25] error: IEnableLogger: Failed to invoke post-install: System.NotSupportedException: Built-in COM has been disabled via a feature switch. See https://aka.ms/dotnet-illink/com for more information.
   at Squirrel.Shell.ShellLink..ctor()
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass5_1.<CreateShortcutsForExecutable>b__1()
   at Squirrel.Utility.<>c__DisplayClass8_0.<Retry>b__0()
   at Squirrel.Utility.Retry[T](Func1 block, Int32 retries)
   at Squirrel.Utility.Retry(Action block, Int32 retries)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass5_1.<CreateShortcutsForExecutable>b__0()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.UpdateManager.ApplyReleasesImpl.CreateShortcutsForExecutable(String exeName, ShortcutLocation locations, Boolean updateOnly, String programArguments, String icon)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<invokePostInstall>b__4(String x)
   at System.Collections.Generic.List1.ForEach(Action1 )
   at Squirrel.UpdateManager.ApplyReleasesImpl.invokePostInstall(SemanticVersion currentVersion, Boolean isInitialInstall, Boolean firstRunOnly, Boolean silentInstall)
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Func1 block)
[13/12/21 12:25:25] fatal: Finished with unhandled exception: System.AggregateException: One or more errors occurred. (Built-in COM has been disabled via a feature switch. See https://aka.ms/dotnet-illink/com for more information.)
 ---> System.NotSupportedException: Built-in COM has been disabled via a feature switch. See https://aka.ms/dotnet-illink/com for more information.
   at Squirrel.Shell.ShellLink..ctor()
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass5_1.<CreateShortcutsForExecutable>b__1()
   at Squirrel.Utility.<>c__DisplayClass8_0.<Retry>b__0()
   at Squirrel.Utility.Retry[T](Func1 block, Int32 retries)
   at Squirrel.Utility.Retry(Action block, Int32 retries)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass5_1.<CreateShortcutsForExecutable>b__0()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.UpdateManager.ApplyReleasesImpl.CreateShortcutsForExecutable(String exeName, ShortcutLocation locations, Boolean updateOnly, String programArguments, String icon)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<invokePostInstall>b__4(String x)
   at System.Collections.Generic.List1.ForEach(Action1 )
   at Squirrel.UpdateManager.ApplyReleasesImpl.invokePostInstall(SemanticVersion currentVersion, Boolean isInitialInstall, Boolean firstRunOnly, Boolean silentInstall)
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Func1 block)
   at Squirrel.UpdateManager.ApplyReleasesImpl.ApplyReleases(UpdateInfo updateInfo, Boolean silentInstall, Boolean attemptingFullInstall, Action1 progress)
   at Squirrel.UpdateManager.FullInstall(Boolean silentInstall, Action1 progress)
   at Squirrel.Update.Program.Install(Boolean silentInstall, ProgressSource progressSource, String sourceDirectory)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)

The application itself was not changed.
Do you
