### ISSUE TITLE
Restart app is failing

### ISSUE THREAD

**Issue by osnoser1** [clowd/Clowd.Squirrel#144]
When I use `UpdateManager.RestartApp()`, it doesn't work and I see this error in the log:
```
2023-01-29 21:24:55.9643 [INFO] - Program: Starting Squirrel Updater: --processStartAndWait C:\Users\Windows 7\AppData\Local\CianzDesktop\app-1.17.0\cianz.exe
2023-01-29 21:24:56.1706 [INFO] - Program: Want to launch 'C:\Users\Windows'
2023-01-29 21:24:56.2866 [FATAL] - Finished with unhandled exception: System.ArgumentException: Value does not fall within the expected range.
   at Squirrel.Update.Program.ProcessStart(String exeName, String arguments, Boolean shouldWait) in ./Program.cs:line 497
   at Squirrel.Update.Program.executeCommandLine(String[] args) in ./Program.cs:line 126
   at Squirrel.Update.Program.main(String[] args) in ./Program.cs:line 60
```

It looks like a problem with the spaces in the path.

**Comment by osnoser1** [comment]
I created am account user without spaces and the problem is gone, but we don't control the user names 😅

**Comment by caesay** [comment]
Thanks for this report, what version of Squirrel are you using?

**Comment by osnoser1** [comment]
Sorry the delay @caesay, the version I'm using is 2.9.42

**Comment by caesay** [comment]
I will shortly deploy a release with this fixed
