### ISSUE TITLE
PlaceHolderNotfoundInAppHostException during Squirrel realisify

### ISSUE THREAD

**Issue by chasewallis** [clowd/Clowd.Squirrel#36]
I have a .net48 project, planning on upgrading to .net6 as soon as I get upgrading figured out. Using 2.7.89-pre and following the examples on the front page readme, I do a simple Squirrel.exe pack and get a PlaceHolderNotfoundInAppHostException.

I tried .39-pre and got the same error. .34-pre would caused my code not to compile, so I didn't check any other versions.
I noticed that IsSingleFileBundle is passing in the `Update.exe`, so I deleted and restored the nuget cache to ensure it wasn't a corrupt file.

I haven't been able to determine if the Update.exe file is actually in the temp location as it is cleaned up directly after the error.

```
~\.nuget\packages\clowd.squirrel\2.7.89-pre\tools\Squirrel.exe pack --packId "Simulator" --packVersion "1.0.0" --packDirectory .\bin\net48\ --releaseDir C:\Users\chase_wallis\SimulatorRelease\

[INFO] NugetConsole: Starting to package 'C:\Users\chase_wallis\AppData\Local\SquirrelClowdTemp\tempa\Simulator.nuspec'
[INFO] NugetConsole: Successfully created package 'C:\Users\chase_wallis\AppData\Local\SquirrelClowdTemp\tempa\Simulator.1.0.0.nupkg'.

[ERRO] Microsoft.NET.HostModel.AppHost.PlaceHolderNotFoundInAppHostException: Exception of type 'Microsoft.NET.HostModel.AppHost.PlaceHolderNotFoundInAppHostException' was thrown.
   at Microsoft.NET.HostModel.AppHost.HostWriter.<>c__DisplayClass4_0.<IsBundle>g__FindBundleHeader|0() in ./HostModel/AppHost/HostWriter.cs:line 234
   at Microsoft.NET.HostModel.RetryUtil.RetryOnIOError(Action func) in ./HostModel/AppHost/RetryUtil.cs:line 32
   at Microsoft.NET.HostModel.AppHost.HostWriter.IsBundle(String appHostFilePath, Int64& bundleHeaderOffset) in ./HostModel/AppHost/HostWriter.cs:line 242
   at SquirrelCli.SingleFileBundle.IsSingleFileBundle(String peFile) in ./SingleFileBundle.cs:line 30
   at SquirrelCli.Program.Releasify(ReleasifyOptions options) in ./Program.cs:line 161
   at SquirrelCli.Program.Pack(PackOptions options) in ./Program.cs:line 124
   at SquirrelCli.CommandAction`1.Execute(IEnumerable`1 args) in ./ValidatedOptionSet.cs:line 160
   at SquirrelCli.CommandSet.Execute(String[] args) in ./ValidatedOptionSet.cs:line 194
   at SquirrelCli.Program.Main(String[] args) in ./Program.cs:line 77
```

**Comment by caesay** [comment]
Hi, thanks for reporting and happy to look at possibly fixing this or improving the error message. Can you explain more how you would run into the situation where there will be an "Update.exe" in the current working directory that is not the Update.exe from Clowd.Squirrel?
