### ISSUE TITLE
Out of memory error when creating Setup.exe bundle

### ISSUE THREAD

**Issue by trrahul** [clowd/Clowd.Squirrel#38]
Hi. I am unable to create the executable after I did it a couple of times. The command is stopping with the following exception. My published files are about 2.2Gb and the NuGet package it creates is 730MB.

```
❯         Squirrel.exe pack --packId "app" --packVersion $buildVersion --packDirectory $publishPath
[INFO] NugetConsole: Starting to package 'C:\Users\Rahul\AppData\Local\SquirrelClowdTemp\tempm\app.nuspec'
[INFO] NugetConsole: Successfully created package 'C:\Users\Rahul\AppData\Local\SquirrelClowdTemp\tempm\app.2.2.0.nupkg'.
[INFO] Program: Creating release package: E:\workspace\ReleaseFiles\Releases\app.2.2.0.nupkg
[INFO] ReleasePackage: Creating release package: E:\workspace\ReleaseFiles\Releases\app.2.2.0.nupkg => E:\workspace\ReleaseFiles\Releases\app-2.2.0-full.nupkg
[INFO] ReleasePackage: Removing unnecessary data
[INFO] ReleasePackage: No release notes found in C:\Users\Rahul\AppData\Local\SquirrelClowdTemp\tempo\app.nuspec
[INFO] Program: Package architecture: X64 (implicit, from a SquirrelAware binary)
[INFO] Program: Creating stub executables
[INFO] EasyZip: Compressing 'C:\Users\Rahul\AppData\Local\SquirrelClowdTemp\tempo' to 'E:\workspace\ReleaseFiles\Releases\app-2.2.0-full.nupkg'...


[INFO] Program: Creating Setup bundle

[ERRO] System.ComponentModel.Win32Exception (0x80070008): Not enough memory resources are available to process this command.
   at Microsoft.NET.HostModel.ResourceUpdater.ThrowExceptionForLastWin32Error() in ./Internal/ResourceUpdater.cs:line 472
   at Microsoft.NET.HostModel.ResourceUpdater.AddResource(Byte[] data, String lpType, IntPtr lpName, UInt16 langId) in ./Internal/ResourceUpdater.Squirrel.cs:line 31
   at Squirrel.Lib.BundledSetupInfo.WriteValue(ResourceUpdater updater, Int32 idx, Byte[] buf) in ./Internal/BundledSetupInfo.cs:line 73
   at Squirrel.Lib.BundledSetupInfo.WriteToFile(String exePath) in ./Internal/BundledSetupInfo.cs:line 58
   at SquirrelCli.Program.Releasify(ReleasifyOptions options) in ./Program.cs:line 324
   at SquirrelCli.Program.Pack(PackOptions options) in ./Program.cs:line 124
   at SquirrelCli.CommandAction`1.Execute(IEnumerable`1 args) in ./ValidatedOptionSet.cs:line 160
   at SquirrelCli.CommandSet.Execute(String[] args) in ./ValidatedOptionSet.cs:line 194
   at SquirrelCli.Program.Main(String[] args) in ./Program.cs:line 77



Squirrel (2.7.98-pre+88e1cc) command line tool for creating and deploying Squirrel releases
Usage: Squirrel.exe [verb] [--option:value]

Package Authoring:

pack: Creates a Squirrel release from a folder containing application files
  -r, --releaseDir=DIRECTORY      Output DIRECTORY for releasified packages
  -u, --packId=ID                 Unique ID for release
  -v, --packVersion=VERSION       Current VERSION for release
  -p, --packDir=DIRECTORY         DIRECTORY containing application files for release
      --packTitle=NAME            Optional display/friendly NAME for release
      --packAuthors=AUTHORS       Optional company or list of release AUTHORS
      --includePdb                Add *.pdb files to release package
      --releaseNotes=PATH         PATH to file with markdown notes for version
  -n, --signParams=PARAMETERS     Sign files via SignTool.exe using these PARAMETERS
      --signTemplate=COMMAND      Use a custom signing COMMAND. '{{file}}' will be
                                    replaced by the path of the file to sign.
      --noDelta                   Skip the generation of delta packages
  -f, --framework=RUNTIMES        List of required RUNTIMES to install during setup
                                    example: 'net6,vcredist143'
  -s, --splashImage=PATH          PATH to image/gif displayed during installation
  -i, --icon=PATH                 PATH to .ico for Setup.exe and Update.exe
      --appIcon=PATH              PATH to .ico for 'Apps and Features' list
      --msi=BITNESS               Compile a .msi machine-wide deployment tool with the
                                    specified BITNESS. (either 'x86' or 'x64')

releasify: Take an existing nuget package and convert it into a Squirrel release
  -r, --releaseDir=DIRECTORY      Output DIRECTORY for releasified packages
  -p, --package=PATH              PATH to a '.nupkg' package to releasify
  -n, --signParams=PARAMETERS     Sign files via SignTool.exe using these PARAMETERS
      --signTemplate=COMMAND      Use a custom signing COMMAND. '{{file}}' will be
                                    replaced by the path of the file to sign.
      --noDelta                   Skip the generation of delta packages
  -f, --framework=RUNTIMES        List of required RUNTIMES to install during setup
                                    example: 'net6,vcredist143'
  -s, --splashImage=PATH          PATH to image/gif displayed during installation
  -i, --icon=PATH                 PATH to .ico for Setup.exe and Update.exe
      --appIcon=PATH              PATH to .ico for 'Apps and Features' list
      --msi=BITNESS               Compile a .msi machine-wide deployment tool with the
                                    specified BITNESS. (either 'x86' or 'x64')

Package Deployment / Syncing:

b2-down: Download recent releases from BackBlaze B2
b2-up: Upload releases to BackBlaze B2
  -r, --releaseDir=DIRECTORY      Output DIRECTORY for releasified packages
      --b2BucketId=VALUE
      --b2keyid=VALUE
      --b2key=VALUE

http-down: Download recent releases from an HTTP source
  -r, --releaseDir=DIRECTORY      Output DIRECTORY for releasified packages
      --url=VALUE                 Base url to the http location with hosted releases

github-down: Download recent releases from GitHub
  -r, --releaseDir=DIRECTORY      Output DIRECTORY for releasified packages
      --repoUrl=VALUE             Full url to the github repository
                                    example: 'https://github.com/myname/myrepo'
      --token=VALUE               OAuth token to use as login credentials
```

**Comment by caesay** [comment]
How much RAM do you have installed?

Creating (and extracting) Setup.exe bundles currently happens in memory and the moment is not designed to support packages this large. I might be able to improve this somewhat on the Squirrel side, but I'm not convinced that [User32 UpdateResource](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-updateresourcew) can handle files this large.

**Comment by trrahul** [comment]
I have 16 GB RAM and I think visual studio was using a lot of the available memory. I will try running the command again with an eye on the memory usage.

**Comment by trrahul** [comment]
I checked and the process was using only around 200 MB when the error happened and the whole memory usage was at 45%.

**Comment by trrahul** [comment]
I resolved this issue by adding /p:RuntimeIdentifier=win-x64 to MsBuild command and it results in a smaller build which brought down the package size to 340 MB. Now there is no error and the installer is created.

**Comment by caesay** [comment]
I have rewritten the setup architecture in 01aab4d7637a55a8bdde81b841f688bac643ead1 to be more cross-platform friendly and we no longer need to load packages into memory to create setup bundles (or extract them while installing)
