### ISSUE TITLE
Issue creating stub executables on AWS EC2 machine

### ISSUE THREAD

**Issue by caesay** [clowd/Clowd.Squirrel#46]
From Discord: 

```txt
I'm back at this problem--it's been a while since I resumed the work. I upgraded to 2.8.1 and still get it. It's a Windows build box. [INFO] Program: Package architecture: X86 (implicit, from a SquirrelAware binary)
[INFO] Program: Creating stub executables
[ERRO] System.AggregateException: One or more errors occurred. (The system cannot open the device or file specified.)
 ---> System.ComponentModel.Win32Exception (0x8007006E): The system cannot open the device or file specified.
   at Microsoft.NET.HostModel.ResourceUpdater.ThrowExceptionForLastWin32Error() in ./Internal/ResourceUpdater.cs:line 472
   at Microsoft.NET.HostModel.ResourceUpdater.Update() in ./Internal/ResourceUpdater.cs:line 367
   at SquirrelCli.Program.createExecutableStubForExe(String exeToCopy) in ./Program.cs:line 388
   at Squirrel.Utility.<>cDisplayClass20_1`1.<<ForEachAsync>b1>d.MoveNext() in ./Internal/Utility.cs:line 323
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at SquirrelCli.Program.<>cDisplayClass4_0.<Releasify>b9(String pkgPath, ZipPackage zpkg) in ./Program.cs:line 237
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, Func2 releaseNotesProcessor, Action2 contentsPostProcessHook) in ./Internal/ReleasePackage.cs:line 123
   at SquirrelCli.Program.Releasify(ReleasifyOptions options) in ./Program.cs:line 187
   at SquirrelCli.Program.Pack(PackOptions options) in ./Program.cs:line 126
   at SquirrelCli.CommandAction1.Execute(IEnumerable1 args) in ./ValidatedOptionSet.cs:line 160
   at SquirrelCli.CommandSet.Execute(String[] args) in ./ValidatedOptionSet.cs:line 194
   at SquirrelCli.Program.Main(String[] args) in ./Program.cs:line 79
Squirrel (2.8.1-pre+bba777)
```

Build machine info:
Windows VM run via gitlab yaml pipeline
74GB free on C
245GB free on D
MSbuild 16.5.012.403
what other info do you need?
Uses General purpose ssd drives: gp2 hosted on Amazon EBS / elastic compute
OsName                                                  : Microsoft Windows Server 2019 Datacenter
OsType                                                  : WINNT
OsOperatingSystemSKU                                    : DatacenterServerEdition
OsVersion                                               : 10.0.17763
16GB RAM, 4 vCPU

Probably need to add some retry logic in and around the ResourceManager.Update method.

**Comment by caesay** [comment]
This is closed [by 2.8.15-pre](https://github.com/clowd/Clowd.Squirrel/releases/tag/2.8.15-pre).
