### ISSUE TITLE
 Creating stub executables

### ISSUE THREAD

**Issue by farima-sedghi** [clowd/Clowd.Squirrel#48]
[ERRO] System.AggregateException: One or more errors occurred. (The data is invalid.)
 ---> System.ComponentModel.Win32Exception (0x8007000D): The data is invalid.
   at Microsoft.NET.HostModel.ResourceUpdater.ThrowExceptionForLastWin32Error() in ./Internal/ResourceUpdater.cs:line 472
   at Microsoft.NET.HostModel.ResourceUpdater.Update() in ./Internal/ResourceUpdater.cs:line 367
   at SquirrelCli.Program.createExecutableStubForExe(String exeToCopy) in ./Program.cs:line 388
   at Squirrel.Utility.<>c__DisplayClass20_1`1.<<ForEachAsync>b__1>d.MoveNext() in ./Internal/Utility.cs:line 323
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at SquirrelCli.Program.<>c__DisplayClass4_0.<Releasify>b__9(String pkgPath, ZipPackage zpkg) in ./Program.cs:line 237
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, Func`2 releaseNotesProcessor, Action`2 contentsPostProcessHook) in ./Internal/ReleasePackage.cs:line 123
   at SquirrelCli.Program.Releasify(ReleasifyOptions options) in ./Program.cs:line 187
   at SquirrelCli.Program.Pack(PackOptions options) in ./Program.cs:line 126
   at SquirrelCli.CommandAction`1.Execute(IEnumerable`1 args) in ./ValidatedOptionSet.cs:line 160
   at SquirrelCli.CommandSet.Execute(String[] args) in ./ValidatedOptionSet.cs:line 194
   at SquirrelCli.Program.Main(String[] args) in ./Program.cs:line 79

**Comment by farima-sedghi** [comment]
its solved with  update
