### ISSUE TITLE
HTTP-DOWN error

### ISSUE THREAD

**Issue by chrisrestall** [clowd/Clowd.Squirrel#62]
Attempting to use the command to try and pull down my packages for delta creation but getting an error.  I'm hosting it locally on IIS (not 100% sure I'm hosting it right either but the command seems to try and grab the file but errors..,.

PS C:\tools\Clowd_squirrel> Squirrel http-down --url "http://localhost:8091/"
Trying to download RELEASES index from http://localhost:8091/RELEASES
Downloading release from http://localhost:8091/VODA-1.0.0-full.nupkg
Downloading release from http://localhost:8091/VODA-1.0.0-full.nupkg
Downloading release from http://localhost:8091/VODA-1.0.0-full.nupkg
Downloading release from http://localhost:8091/VODA-1.0.0-full.nupkg

[ERRO] System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 500 (Internal Server Error).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Squirrel.HttpClientFileDownloader.DownloadToStreamInternal(HttpClient client, String requestUri, Stream destination, Action`1 progress, CancellationToken cancellationToken) in ./FileDownloader.cs:line 102
   at Squirrel.HttpClientFileDownloader.DownloadFile(String url, String targetFile, Action`1 progress, String authorization) in ./FileDownloader.cs:line 63
   at SquirrelCli.Sources.SimpleWebRepository.downloadRelease(String localPath, Uri remoteUrl) in ./Sync/SimpleWebRepository.cs:line 65
   at SquirrelCli.Sources.SimpleWebRepository.<>c__DisplayClass7_0.<<retryAsync>b__0>d.MoveNext() in ./Sync/SimpleWebRepository.cs:line 85
--- End of stack trace from previous location ---
   at SquirrelCli.Sources.SimpleWebRepository.retryAsync[T](Int32 count, Func`1 block) in ./Sync/SimpleWebRepository.cs:line 74
   at SquirrelCli.Sources.SimpleWebRepository.retryAsync(Int32 count, Func`1 block) in ./Sync/SimpleWebRepository.cs:line 85
   at SquirrelCli.Sources.SimpleWebRepository.SyncRemoteReleases(Uri targetUri, DirectoryInfo releasesDir) in ./Sync/SimpleWebRepository.cs:line 42
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at SquirrelCli.Program.Download[T](T repo) in ./Program.cs:line 114
   at SquirrelCli.Program.<>c.<Main>b__4_5(SyncHttpOptions o) in ./Program.cs:line 65
   at SquirrelCli.CommandAction`1.Execute(IEnumerable`1 args) in ./ValidatedOptionSet.cs:line 160
   at SquirrelCli.CommandSet.Execute(String[] args) in ./ValidatedOptionSet.cs:line 195
   at SquirrelCli.Program.Main(String[] args) in ./Program.cs:line 87

**Comment by chrisrestall** [comment]
nevermind - I had a typo..
