### ISSUE TITLE
DirectoryNotFoundException when using http-down when releases directory is specified and doesn't exist.

### ISSUE THREAD

**Issue by ComtelJeremy** [clowd/Clowd.Squirrel#93]
Hello,

This line

https://github.com/clowd/Clowd.Squirrel/blob/2f27e5d84cf9559eb510dcd37893f17e98bd3416/src/SquirrelCli/Sync/SimpleWebRepository.cs#L30

throws the following when there is no existing directory. Should Squirrel create it if it doesn't exist?

```
[ERRO] System.AggregateException: One or more errors occurred. (Could not find a part of the path 'C:\GIT\Porject\releases\RELEASES'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\GIT\Project\releases\RELEASES'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String , FileMode , FileAccess , FileShare , FileOptions )
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.SyncWindowsFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream , String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , Boolean )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 )
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String , Boolean , Encoding , Int32 )
   at System.IO.StreamWriter..ctor(String , Boolean , Encoding , Int32 )
   at System.IO.StreamWriter..ctor(String )
   at System.IO.File.WriteAllText(String , String )
   at SquirrelCli.Sources.SimpleWebRepository.SyncRemoteReleases(Uri targetUri, DirectoryInfo releasesDir) in ./Sync/SimpleWebRepository.cs:line 30
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at SquirrelCli.Program.Download[T](T repo) in ./Program.cs:line 114
   at SquirrelCli.Program.<>c.<Main>b__4_5(SyncHttpOptions o) in ./Program.cs:line 65
   at SquirrelCli.CommandAction`1.Execute(IEnumerable`1 args) in ./ValidatedOptionSet.cs:line 168
   at SquirrelCli.Program.Main(String[] args) in ./Program.cs:line 87
```

**Comment by caesay** [comment]
Hi, thanks for reporting! This issue has been fixed in v3 by the following line https://github.com/clowd/Clowd.Squirrel/blob/develop/src/Squirrel.CommandLine/SyncOptions.cs#L16 - as there have been many changes to the way that repositories work in v3 I do not believe I will be backporting this fix to v2.
